export const homeObjOne = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Berry Cardinal",
  headline: "Metal",
  description:"           Berry Cardinal, 1 of 100",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/berry.png",
  imgDesc: "images/berry.png",
  alt: "NFT",
  payLink: "https://pool.pm/asset1tcxnum3xsryqls3hhyc0cu5lhlshnusxf4cl5r",
  item: "/item1",
  type: "BerryNFT",
  textCard: "Berry Cardinal",
  price: ""
};

export const homeObjTwo = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Clay Nation",
  headline: "Clay Nation NFT",
  description:
    "The original handmade Clay NFTs - doubling as entry to Clay Nation & moulding the metaverse.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/Clay180.png",
  imgDesc: "Clay Mates #180",
  img2: "images/Clay851.png",
  img2Desc: "Clay Mates #851",
  img3: "images/Clay651.png",
  img3Desc: "Clay Mates #651",
  img4: "images/Clay1251.png",
  img4Desc: "Clay Mates #1251",
  alt: "NFT",
  payLink: "https://pool.pm/stake1uy8dkkxsmnltmnjyntwnr3y4mczkd3plrn06dve9k7gcm6szgjm3x/%4040fa2aa6",
  item: "/item2",
  type: "ClayNationNFT",
  textCard: "Clay Nation NFT",
  price: ""
};

export const homeObjThree = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Space Bud",
  headline: "Space Bud NFT",
  description:
    "As a line of code revealed the yet unknown, something peculiar was about to happen in selected places on planet earth. Seemingly out of nowhere, the chosen ones would come together and embark on the biggest adventure of their lifetimes. Spacebudz holders would soon find out, but right now, they were still unaware, completely oblivious to their destiny.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/spacebud83.png",
  imgDesc: "Space bud #83",
  img2: "images/spacebud80.png",
  img2Desc: "Space bud #80",
  img3: "images/spacebud239.png",
  img3Desc: "Space bud #239",
  img4: "images/spacebud837.png",
  img4Desc: "Space bud #837",
  alt: "NFT",
  payLink: "https://pool.pm/addr1q9alg4uys4qqg0307jpu0esxf3wwr6epfqxmrjrl2jmegsqwmdvdph87hh8yfxkax8zfths9vmzr78xl56ejtdu33h4qlmkr4x/%40d5e6bf05",
  item: "/item3",
  type: "SpacebudNft",
  textCard: "PXL",
  price: ""
};

export const homeObjFour = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Nurive",
  headline: "Entre Luces y sombras",
  description:"Ver las obras de Nurive es entrar a un espacio magico en donde los personajes, como duendes o sombras, cuentan su historia y expresan el amor, el juego y la belleza.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Buy",
  imgStart: "start",
  img: "images/nuricuadro.jpeg",
  img2: "images/NuriLogo.webp",
  img3: "images/svg-1.svg",
  img: "images/spacebud83.png",
  imgDesc: "Genesis Token",
  img2Desc: "Genesis Token",
  img3Desc: "Genesis Token",
  img4Desc: "Member Token",
  img5Desc: "Member Token",
  alt: "NFT",
  payLink: "https://mpago.la/2qg7LET",
  item: "/Item4",
  type: "metal",
  textCard: "Arre unicornio metal",
  price: ""
};

export const homeObjFive = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "PXL",
  headline: "PXL NFT",
  description:
    "DEADPXLZ is a project which started out in March 2021. It was born out of the desire to not do something different only for the sake of doing it but to build and innovate as well as bring people together in a flourishing community of likeminded individuals..",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/pxl251.png",
  imgDesc: "pxl #251",
  img2: "images/pxl1037.png",
  img2Desc: "pxl #1037",
  img3: "images/pxl #1181.png",
  img3Desc: "pxl #1181",
  img4: "images/pxl1317.png",
  img4Desc: "pxl #1317",
  alt: "NFT",
  payLink: "https://pool.pm/addr1q9alg4uys4qqg0307jpu0esxf3wwr6epfqxmrjrl2jmegsqwmdvdph87hh8yfxkax8zfths9vmzr78xl56ejtdu33h4qlmkr4x/%401ec85dce",
  item: "/item5",
  type: "PXLNft",
  textCard: "PXL",
  price: ""
};

export const homeObjSix = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Pavia",
  headline: "Pavia NFT",
  description:
    "In September 1501 Pavia Italy was the birthplace of Gerolamo (Jerome) Cardano, whom the Cardano blockchain project was named after. 2021 sees the launch of Pavia.io which is a metaverse being built on Cardano. It seems fitting to name our virtual world Pavia.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/Pavia64-113.png",
  imgDesc: "Pavia token",
  img2: "images/Pavia64-113.png",
  img2Desc: "Pavia token",
  img3: "images/Pavia64-113.png",
  img3Desc: "Pavia token",
  img4: "images/Pavia64-113.png",
  img4Desc: "Pavia token",
  alt: "NFT",
  payLink: "https://pool.pm/addr1q9alg4uys4qqg0307jpu0esxf3wwr6epfqxmrjrl2jmegsqwmdvdph87hh8yfxkax8zfths9vmzr78xl56ejtdu33h4qlmkr4x/%404bf184e0",
  item: "/item6",
  type: "PaviaNft",
  textCard: "Pavia",
  price: ""
};

export const homeObjSeven = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Arre Unicornio",
  headline: "Metal",
  description:
    "Ver las obras de Nurive es entrar a un espacio magico en donde los personajes, como duendes o sombras, cuentan su historia y expresan el amor, el juego y la belleza.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/laguna.webp",
  img2: "images/NuriLogo.webp",
  img3: "images/svg-1.svg",
  alt: "NFT",
  payLink: "https://mpago.la/2qg7LET",
  item: "/item4",
  type: "metal",
  textCard: "Arre unicornio metal",
  price: "$4800"
};

export const homeObjEight = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Arre Unicornio",
  headline: "Metal",
  description:
    "Ver las obras de Nurive es entrar a un espacio magico en donde los personajes, como duendes o sombras, cuentan su historia y expresan el amor, el juego y la belleza.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/laguna.webp",
  img2: "images/NuriLogo.webp",
  img3: "images/svg-1.svg",
  alt: "NFT",
  payLink: "https://mpago.la/2qg7LET",
  item: "/item4",
  type: "metal",
  textCard: "Arre unicornio metal",
  price: "$4800"
};

export const homeObjNine = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Arre Unicornio",
  headline: "Metal",
  description:
    "Ver las obras de Nurive es entrar a un espacio magico en donde los personajes, como duendes o sombras, cuentan su historia y expresan el amor, el juego y la belleza.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/laguna.webp",
  img2: "images/NuriLogo.webp",
  img3: "images/svg-1.svg",
  alt: "NFT",
  payLink: "https://mpago.la/2qg7LET",
  item: "/item4",
  type: "metal",
  textCard: "Arre unicornio metal",
  price: "$4800"
};

export const homeObjTen = {
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Arre Unicornio",
  headline: "Metal",
  description:
    "Ver las obras de Nurive es entrar a un espacio magico en donde los personajes, como duendes o sombras, cuentan su historia y expresan el amor, el juego y la belleza.",
  description2:  "Stay protected 24/7 anywhere anytime",
  metering: "Medidas: 40 x 40 cm.",
  buttonLabel: "Ver en la red",
  imgStart: "start",
  img: "images/laguna.webp",
  img2: "images/NuriLogo.webp",
  img3: "images/svg-1.svg",
  alt: "NFT",
  payLink: "https://mpago.la/2qg7LET",
  item: "/item4",
  type: "metal",
  textCard: "Arre unicornio metal",
  price: "$4800"
};